### ISSUE TITLE
check_service sqlite database connection stuck

### ISSUE THREAD

**Issue by dfateyev** [release-monitoring/anitya#821]
Hello there,
A "check_service" instance being run as a service blocks SQLite DB shortly after startup:
```
Sep 02 11:14:59 python3.4[19272]: [sqlalchemy.pool.NullPool ERROR] Exception during reset or similar
Sep 02 11:14:59 python3.4[19272]: Traceback (most recent call last):
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
Sep 02 11:14:59 python3.4[19272]: fairy._reset(pool)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 701, in _reset
Sep 02 11:14:59 python3.4[19272]: pool._dialect.do_rollback(self)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 406, in do_rollback
Sep 02 11:14:59 python3.4[19272]: dbapi_connection.rollback()
Sep 02 11:14:59 python3.4[19272]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 14
Sep 02 11:14:59 python3.4[19272]: [sqlalchemy.pool.NullPool ERROR] Exception closing connection <sqlite3.Connection object at 0x7f5c830e48f0>
Sep 02 11:14:59 python3.4[19272]: Traceback (most recent call last):
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
Sep 02 11:14:59 python3.4[19272]: fairy._reset(pool)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 701, in _reset
Sep 02 11:14:59 python3.4[19272]: pool._dialect.do_rollback(self)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 406, in do_rollback
Sep 02 11:14:59 python3.4[19272]: dbapi_connection.rollback()
Sep 02 11:14:59 python3.4[19272]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 14
Sep 02 11:14:59 python3.4[19272]: During handling of the above exception, another exception occurred:
Sep 02 11:14:59 python3.4[19272]: Traceback (most recent call last):
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 250, in _close_connection
Sep 02 11:14:59 python3.4[19272]: self._dialect.do_close(connection)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 412, in do_close
Sep 02 11:14:59 python3.4[19272]: dbapi_connection.close()
Sep 02 11:14:59 python3.4[19272]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 14
Sep 02 11:14:59 python3.4[19272]: [sqlalchemy.pool.NullPool ERROR] Exception during reset or similar
Sep 02 11:14:59 python3.4[19272]: Traceback (most recent call last):
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
Sep 02 11:14:59 python3.4[19272]: fairy._reset(pool)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 701, in _reset
Sep 02 11:14:59 python3.4[19272]: pool._dialect.do_rollback(self)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 406, in do_rollback
Sep 02 11:14:59 python3.4[19272]: dbapi_connection.rollback()
Sep 02 11:14:59 python3.4[19272]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 14
Sep 02 11:14:59 python3.4[19272]: [sqlalchemy.pool.NullPool ERROR] Exception closing connection <sqlite3.Connection object at 0x7f5c81a02570>
Sep 02 11:14:59 python3.4[19272]: Traceback (most recent call last):
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
Sep 02 11:14:59 python3.4[19272]: fairy._reset(pool)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 701, in _reset
Sep 02 11:14:59 python3.4[19272]: pool._dialect.do_rollback(self)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 406, in do_rollback
Sep 02 11:14:59 python3.4[19272]: dbapi_connection.rollback()
Sep 02 11:14:59 python3.4[19272]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 14
Sep 02 11:14:59 python3.4[19272]: During handling of the above exception, another exception occurred:
Sep 02 11:14:59 python3.4[19272]: Traceback (most recent call last):
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 250, in _close_connection
Sep 02 11:14:59 python3.4[19272]: self._dialect.do_close(connection)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 412, in do_close
Sep 02 11:14:59 python3.4[19272]: dbapi_connection.close()
Sep 02 11:14:59 python3.4[19272]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 14
Sep 02 11:14:59 python3.4[19272]: [sqlalchemy.pool.NullPool ERROR] Exception during reset or similar
Sep 02 11:14:59 python3.4[19272]: Traceback (most recent call last):
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
Sep 02 11:14:59 python3.4[19272]: fairy._reset(pool)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 701, in _reset
Sep 02 11:14:59 python3.4[19272]: pool._dialect.do_rollback(self)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 406, in do_rollback
Sep 02 11:14:59 python3.4[19272]: dbapi_connection.rollback()
Sep 02 11:14:59 python3.4[19272]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 14
Sep 02 11:14:59 python3.4[19272]: [sqlalchemy.pool.NullPool ERROR] Exception closing connection <sqlite3.Connection object at 0x7f5c818d4b90>
Sep 02 11:14:59 python3.4[19272]: Traceback (most recent call last):
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
Sep 02 11:14:59 python3.4[19272]: fairy._reset(pool)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 701, in _reset
Sep 02 11:14:59 python3.4[19272]: pool._dialect.do_rollback(self)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 406, in do_rollback
Sep 02 11:14:59 python3.4[19272]: dbapi_connection.rollback()
Sep 02 11:14:59 python3.4[19272]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 14
Sep 02 11:14:59 python3.4[19272]: During handling of the above exception, another exception occurred:
Sep 02 11:14:59 python3.4[19272]: Traceback (most recent call last):
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 250, in _close_connection
Sep 02 11:14:59 python3.4[19272]: self._dialect.do_close(connection)
Sep 02 11:14:59 python3.4[19272]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 412, in do_close
Sep 02 11:14:59 python3.4[19272]: dbapi_connection.close()
Sep 02 11:14:59 python3.4[19272]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 14
```
In "ps" output, there is a bunch of file open attempts generated by "check_service" instance:

```
python3.4 19272           root  mem       REG         182,811025     85872    263122 /opt/rh/rh-python34/root/usr/lib64/python3.4/lib-dynload/_sqlite3.cpython-34m.so
python3.4 19272           root  mem       REG         182,811025    753232    395694 /usr/lib64/libsqlite3.so.0.8.6
python3.4 19272           root    9u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
python3.4 19272           root   11u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
python3.4 19272           root   12u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
python3.4 19272           root   14u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
python3.4 19272           root   15u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
python3.4 19272           root   16u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
python3.4 19272           root   17u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
python3.4 19272           root   18u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
python3.4 19272           root   19u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
python3.4 19272           root   23u      REG         182,811025    507904    533563 /opt/rh/httpd24/root/var/www/anitya-dev.sqlite
```
As for the details, "check_service" currently run under systemd, with root privileges, uses python-3.4.

**Comment by Zlopez** [comment]
To be honest I don't use SQLite for a while and this is known issue of the SQLite database. You can't work with SQLite object in multiple threads.
check_service is running multiple threads in parallel to be able to go through projects quickly.

If you find what call is problematic for SQLite, I could try to fix it.
